Repository octokit/plugin-enterprise-server.js, pull requests merged in 2023-06, with the labels that each got.

#572 Generation script should give types imported correctly
  scripts/update-endpoints/code.js
Labels: Type: Maintenance

#571 fix(build): switch to esbuild from pika
  package-lock.json
  package.json
  scripts/build.mjs
  src/endpoints-to-methods.ts
  src/types.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#564 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: Type: Breaking change, Type: Maintenance

#574 docs(README): typo fixes
  README.md
Labels: Type: Documentation

#580 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
